/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TailorRouteImport } from './routes/tailor'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUserRouteImport } from './routes/dashboard.user'
import { Route as DashboardTailorRouteImport } from './routes/dashboard.tailor'
import { Route as DashboardUserMessagesRouteImport } from './routes/dashboard.user.messages'
import { Route as DashboardTailorMessagesRouteImport } from './routes/dashboard.tailor.messages'

const TailorRoute = TailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUserRoute = DashboardUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTailorRoute = DashboardTailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUserMessagesRoute = DashboardUserMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardUserRoute,
} as any)
const DashboardTailorMessagesRoute = DashboardTailorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardTailorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/tailor': typeof TailorRoute
  '/dashboard/tailor': typeof DashboardTailorRouteWithChildren
  '/dashboard/user': typeof DashboardUserRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tailor/messages': typeof DashboardTailorMessagesRoute
  '/dashboard/user/messages': typeof DashboardUserMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/tailor': typeof TailorRoute
  '/dashboard/tailor': typeof DashboardTailorRouteWithChildren
  '/dashboard/user': typeof DashboardUserRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/tailor/messages': typeof DashboardTailorMessagesRoute
  '/dashboard/user/messages': typeof DashboardUserMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/tailor': typeof TailorRoute
  '/dashboard/tailor': typeof DashboardTailorRouteWithChildren
  '/dashboard/user': typeof DashboardUserRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tailor/messages': typeof DashboardTailorMessagesRoute
  '/dashboard/user/messages': typeof DashboardUserMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/register'
    | '/tailor'
    | '/dashboard/tailor'
    | '/dashboard/user'
    | '/dashboard/'
    | '/dashboard/tailor/messages'
    | '/dashboard/user/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/messages'
    | '/register'
    | '/tailor'
    | '/dashboard/tailor'
    | '/dashboard/user'
    | '/dashboard'
    | '/dashboard/tailor/messages'
    | '/dashboard/user/messages'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/register'
    | '/tailor'
    | '/dashboard/tailor'
    | '/dashboard/user'
    | '/dashboard/'
    | '/dashboard/tailor/messages'
    | '/dashboard/user/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  RegisterRoute: typeof RegisterRoute
  TailorRoute: typeof TailorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tailor': {
      id: '/tailor'
      path: '/tailor'
      fullPath: '/tailor'
      preLoaderRoute: typeof TailorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user': {
      id: '/dashboard/user'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tailor': {
      id: '/dashboard/tailor'
      path: '/tailor'
      fullPath: '/dashboard/tailor'
      preLoaderRoute: typeof DashboardTailorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user/messages': {
      id: '/dashboard/user/messages'
      path: '/messages'
      fullPath: '/dashboard/user/messages'
      preLoaderRoute: typeof DashboardUserMessagesRouteImport
      parentRoute: typeof DashboardUserRoute
    }
    '/dashboard/tailor/messages': {
      id: '/dashboard/tailor/messages'
      path: '/messages'
      fullPath: '/dashboard/tailor/messages'
      preLoaderRoute: typeof DashboardTailorMessagesRouteImport
      parentRoute: typeof DashboardTailorRoute
    }
  }
}

interface DashboardTailorRouteChildren {
  DashboardTailorMessagesRoute: typeof DashboardTailorMessagesRoute
}

const DashboardTailorRouteChildren: DashboardTailorRouteChildren = {
  DashboardTailorMessagesRoute: DashboardTailorMessagesRoute,
}

const DashboardTailorRouteWithChildren = DashboardTailorRoute._addFileChildren(
  DashboardTailorRouteChildren,
)

interface DashboardUserRouteChildren {
  DashboardUserMessagesRoute: typeof DashboardUserMessagesRoute
}

const DashboardUserRouteChildren: DashboardUserRouteChildren = {
  DashboardUserMessagesRoute: DashboardUserMessagesRoute,
}

const DashboardUserRouteWithChildren = DashboardUserRoute._addFileChildren(
  DashboardUserRouteChildren,
)

interface DashboardRouteChildren {
  DashboardTailorRoute: typeof DashboardTailorRouteWithChildren
  DashboardUserRoute: typeof DashboardUserRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardTailorRoute: DashboardTailorRouteWithChildren,
  DashboardUserRoute: DashboardUserRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  RegisterRoute: RegisterRoute,
  TailorRoute: TailorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
